apiVersion: v1
kind: Secret
metadata:
  name: minecraft-files-secret
type: Opaque
data:
  # TODO: update these with your own values
  azurestorageaccountname: <base64_encoded_storage_acct_name> # echo -n mystorageaccount | base64 -w 0
  azurestorageaccountkey: <base64_encoded_storage_acct_key> # echo -n `az storage account keys list -n mystorageacct -g myresourcegroup --query '[0].value' -o tsv` | base64 -w 0
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:2.0
        ports:
        - containerPort: 25565
          protocol: TCP
        - containerPort: 25575
          protocol: TCP
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - name: azure
          mountPath: /data
      volumes:
      - name: azure
        azureFile:
          secretName: minecraft-files-secret
          shareName: minecraft-data
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  selector:
    app: minecraft
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
    - name: rcon
      protocol: TCP
      port: 25575
      targetPort: 25575
  type: LoadBalancer